# This is my workflow file

name: JS Actions
on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: "hello-action"
      uses: ./.github/actions/hello-world
      with: 
        third-greeting: "The only user"

    - name: "Shell commands"
      run: |
        ls
        echo $PATH >> testfile.txt
        cat testfile.txt
        ls -a
        echo Complete.
